#!/usr/bin/env node
/**
 * crosspost.mjs — post latest NewsAnarchist articles to all 5 platforms via official APIs.
 *
 * Required env vars (load from credentials.env before running):
 *   X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, X_ACCESS_SECRET
 *   FB_PAGE_ID, FB_ACCESS_TOKEN
 *   IG_USER_ID, IG_ACCESS_TOKEN
 *   LINKEDIN_ACCESS_TOKEN, LINKEDIN_AUTHOR   (urn:li:person:XXX or urn:li:organization:XXX)
 *   THREADS_USER_ID, THREADS_ACCESS_TOKEN
 *
 * Usage:
 *   node scripts/crosspost.mjs               # post newest unposted article
 *   node scripts/crosspost.mjs --slug <slug> # post a specific article
 *   node scripts/crosspost.mjs --dry-run     # print what would be posted, don't post
 */

import { createHmac } from 'crypto';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { homedir } from 'os';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, '..');

// ─── Secrets directory & token readers ───────────────────────────────────────

const SECRETS_DIR = join(homedir(), '.openclaw', 'secrets');

// X credentials live in credentials.env
function _loadXCreds() {
  const credFile = join(SECRETS_DIR, 'credentials.env');
  if (!existsSync(credFile)) return;
  for (const line of readFileSync(credFile, 'utf8').split('\n')) {
    const m = line.match(/^export\s+([A-Z0-9_]+)="?([^"]*)"?/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
_loadXCreds();

// Meta tokens live in flat files (same layout as social-crosspost.mjs)
const FB_TOKEN_FILE      = join(SECRETS_DIR, 'fb-page-token');
const THREADS_TOKEN_FILE = join(SECRETS_DIR, 'threads-token');
const LI_TOKEN_FILE      = join(SECRETS_DIR, 'linkedin-tokens.json');

function readFile(path) { return existsSync(path) ? readFileSync(path, 'utf8').trim() : null; }
function readJson(path) { try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return null; } }

// Hardcoded Meta account IDs (matches social-crosspost.mjs)
const FB_PAGE_ID      = '1074962905699351';
const IG_ACCOUNT_ID   = '17841474528389878';
const THREADS_USER_ID = '36151720161081790';


const SITE_BASE   = 'https://newsanarchist.com';
const IMG_BASE    = `${SITE_BASE}/images/articles`;
const ARTICLES_DB = join(ROOT, 'generated-articles.json');
const POSTED_DB   = join(__dir, 'posted.json');

// ─── CLI args ─────────────────────────────────────────────────────────────────

const args       = process.argv.slice(2);
const DRY_RUN    = args.includes('--dry-run');
const SLUG_IDX   = args.indexOf('--slug');
const FORCE_SLUG = SLUG_IDX !== -1 ? args[SLUG_IDX + 1] : null;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function loadPosted() {
  return existsSync(POSTED_DB) ? JSON.parse(readFileSync(POSTED_DB, 'utf8')) : {};
}

function markPosted(slug, results) {
  const db = loadPosted();
  db[slug] = { postedAt: new Date().toISOString(), platforms: results };
  if (!DRY_RUN) writeFileSync(POSTED_DB, JSON.stringify(db, null, 2));
}

/** Strip HTML tags and collapse whitespace. */
function stripHtml(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Extract the first 2 sentences of real body text from an article HTML file.
 * Returns a string of at most ~280 chars combined.
 */
function extractTeaser(slug) {
  const htmlPath = join(ROOT, 'articles', `${slug}.html`);
  if (!existsSync(htmlPath)) return '';

  const html = readFileSync(htmlPath, 'utf8');

  // Grab the article-body div content
  const bodyMatch = html.match(/<div class="article-body">([\s\S]*?)<\/div>\s*<!-- ARTICLE TAGS/);
  if (!bodyMatch) return '';

  // Boilerplate phrases generated by the AI template — skip these paragraphs
  const BOILERPLATE = [
    'This story originates from',
    'The details have received minimal coverage',
    'which should tell you something',
    'Here\'s what you need to know',
    'Here is what you need to know',
  ];

  // Take first non-empty <p> tags (skip callout boxes, disclosures, boilerplate)
  const paragraphs = [...bodyMatch[1].matchAll(/<p(?![^>]*class)[^>]*>([\s\S]*?)<\/p>/gi)]
    .map(m => stripHtml(m[1]))
    .filter(t => t.length > 20
      && !t.startsWith('Disclosure:')
      && !BOILERPLATE.some(b => t.includes(b)));

  if (!paragraphs.length) return '';

  // Grab sentences from the first paragraph until we have 2
  const sentences = [];
  for (const para of paragraphs) {
    const parts = para.match(/[^.!?]+[.!?]+/g) || [para];
    for (const s of parts) {
      const trimmed = s.trim();
      if (trimmed.length > 10) {
        sentences.push(trimmed);
        if (sentences.length >= 2) break;
      }
    }
    if (sentences.length >= 2) break;
  }

  return sentences.join(' ');
}

/**
 * Build the public image URL for an article.
 * Prefers the stored falUrl (direct fal.ai CDN), falls back to hosted PNG.
 */
function imageUrl(article) {
  if (article.falUrl) return article.falUrl;
  return `${IMG_BASE}/${article.slug}.png`;
}

/** Build the post text (shared across platforms, trimmed per-platform downstream). */
function buildPostText(article, teaser, url, maxLen = 2200) {
  const headline = article.title.toUpperCase();
  let body = `${headline}\n\n${teaser}\n\n${url}`;
  if (body.length > maxLen) {
    const budget = maxLen - headline.length - url.length - 6;
    body = `${headline}\n\n${teaser.slice(0, budget)}…\n\n${url}`;
  }
  return body;
}

// ─── Twitter / X ──────────────────────────────────────────────────────────────

function oauthSign(method, url, params, consumerKey, consumerSecret, tokenSecret) {
  const encoded = (s) => encodeURIComponent(s);
  const sortedParams = Object.entries(params)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `${encoded(k)}=${encoded(v)}`)
    .join('&');
  const baseString = `${method}&${encoded(url)}&${encoded(sortedParams)}`;
  const signingKey = `${encoded(consumerSecret)}&${encoded(tokenSecret)}`;
  return createHmac('sha1', signingKey).update(baseString).digest('base64');
}

function buildOauthHeader(method, url, extraParams, creds) {
  const oauthParams = {
    oauth_consumer_key:     creds.apiKey,
    oauth_nonce:            Math.random().toString(36).slice(2) + Date.now(),
    oauth_signature_method: 'HMAC-SHA1',
    oauth_timestamp:        String(Math.floor(Date.now() / 1000)),
    oauth_token:            creds.accessToken,
    oauth_version:          '1.0',
  };
  const allParams = { ...oauthParams, ...extraParams };
  oauthParams.oauth_signature = oauthSign(
    method, url, allParams, creds.apiKey, creds.apiSecret, creds.accessSecret
  );
  const headerParts = Object.entries(oauthParams)
    .map(([k, v]) => `${k}="${encodeURIComponent(v)}"`)
    .join(', ');
  return `OAuth ${headerParts}`;
}

async function uploadMediaToTwitter(imageUrl, creds) {
  // Download image
  const imgRes = await fetch(imageUrl);
  if (!imgRes.ok) throw new Error(`Image fetch failed: ${imgRes.status}`);
  const imgBuf = Buffer.from(await imgRes.arrayBuffer());

  // Upload via v1.1 multipart
  const uploadUrl = 'https://upload.twitter.com/1.1/media/upload.json';
  const boundary  = `------boundary${Date.now()}`;
  const body      = Buffer.concat([
    Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="media"\r\nContent-Type: image/png\r\n\r\n`),
    imgBuf,
    Buffer.from(`\r\n--${boundary}--`),
  ]);

  const oauthHeader = buildOauthHeader('POST', uploadUrl, {}, creds);
  const res = await fetch(uploadUrl, {
    method: 'POST',
    headers: {
      Authorization:  oauthHeader,
      'Content-Type': `multipart/form-data; boundary=${boundary}`,
    },
    body,
  });
  const json = await res.json();
  if (!res.ok) throw new Error(`Twitter media upload failed: ${JSON.stringify(json)}`);
  return json.media_id_string;
}

async function postToTwitter(article, teaser, artUrl) {
  const creds = {
    apiKey:      process.env.X_CONSUMER_KEY,
    apiSecret:   process.env.X_CONSUMER_SECRET,
    accessToken: process.env.X_ACCESS_TOKEN,
    accessSecret:process.env.X_ACCESS_TOKEN_SECRET,
  };
  if (!creds.apiKey) return { platform: 'twitter', skipped: true, reason: 'missing X credentials' };

  // Twitter max 280 chars; keep headline + teaser snippet + URL
  const url     = artUrl;
  const urlLen  = 23; // t.co wraps all URLs to 23 chars
  const budget  = 280 - urlLen - 4; // 4 for '\n\n' + ' '
  const snippet = teaser.length > budget - article.title.length - 2
    ? teaser.slice(0, budget - article.title.length - 5) + '…'
    : teaser;
  const text = `${article.title}\n\n${snippet}\n\n${url}`;

  try {
    const imgId  = await uploadMediaToTwitter(imageUrl(article), creds);
    const tweetUrl = 'https://api.twitter.com/2/tweets';
    const payload  = { text, media: { media_ids: [imgId] } };
    const body     = JSON.stringify(payload);
    const oauthHeader = buildOauthHeader('POST', tweetUrl, {}, creds);

    const res  = await fetch(tweetUrl, {
      method:  'POST',
      headers: { Authorization: oauthHeader, 'Content-Type': 'application/json' },
      body,
    });
    const json = await res.json();
    if (!res.ok) throw new Error(JSON.stringify(json));
    return { platform: 'twitter', ok: true, id: json.data?.id };
  } catch (err) {
    return { platform: 'twitter', ok: false, error: err.message };
  }
}

// ─── Facebook ─────────────────────────────────────────────────────────────────

async function postToFacebook(article, teaser, artUrl) {
  const token = readFile(FB_TOKEN_FILE);
  if (!token) return { platform: 'facebook', skipped: true, reason: 'missing fb-page-token file' };

  const message = buildPostText(article, teaser, artUrl, 63206);

  try {
    const params = new URLSearchParams({
      message,
      link:         artUrl,
      access_token: token,
    });
    const res  = await fetch(`https://graph.facebook.com/v25.0/${FB_PAGE_ID}/feed`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    params,
    });
    const json = await res.json();
    if (!res.ok || json.error) throw new Error(JSON.stringify(json.error ?? json));
    return { platform: 'facebook', ok: true, id: json.id };
  } catch (err) {
    return { platform: 'facebook', ok: false, error: err.message };
  }
}

// ─── Instagram ────────────────────────────────────────────────────────────────

async function postToInstagram(article, teaser, artUrl) {
  const token = readFile(FB_TOKEN_FILE);
  if (!token) return { platform: 'instagram', skipped: true, reason: 'missing fb-page-token file' };

  const caption = buildPostText(article, teaser, artUrl, 2200);
  const imgSrc  = imageUrl(article);

  try {
    // Step 1 — create media container
    const createParams = new URLSearchParams({
      image_url:    imgSrc,
      caption,
      access_token: token,
    });
    const createRes  = await fetch(`https://graph.facebook.com/v25.0/${IG_ACCOUNT_ID}/media`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    createParams,
    });
    const createJson = await createRes.json();
    if (!createRes.ok || createJson.error) throw new Error(`Container error: ${JSON.stringify(createJson.error ?? createJson)}`);

    const creationId = createJson.id;

    // Step 2 — publish
    const publishParams = new URLSearchParams({ creation_id: creationId, access_token: token });
    const pubRes  = await fetch(`https://graph.facebook.com/v25.0/${IG_ACCOUNT_ID}/media_publish`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    publishParams,
    });
    const pubJson = await pubRes.json();
    if (!pubRes.ok || pubJson.error) throw new Error(`Publish error: ${JSON.stringify(pubJson.error ?? pubJson)}`);

    return { platform: 'instagram', ok: true, id: pubJson.id };
  } catch (err) {
    return { platform: 'instagram', ok: false, error: err.message };
  }
}

// ─── LinkedIn ─────────────────────────────────────────────────────────────────

async function postToLinkedIn(article, teaser, artUrl) {
  const liJson = readJson(LI_TOKEN_FILE);
  const token  = liJson?.access_token;
  const author = liJson?.author ?? liJson?.person_urn ?? liJson?.organizationUrn;
  if (!token || !author) return { platform: 'linkedin', skipped: true, reason: 'missing linkedin-tokens.json or author URN' };

  const commentary = buildPostText(article, teaser, artUrl, 3000);

  const payload = {
    author,
    lifecycleState: 'PUBLISHED',
    specificContent: {
      'com.linkedin.ugc.ShareContent': {
        shareCommentary:   { text: commentary },
        shareMediaCategory: 'ARTICLE',
        media: [{
          status:      'READY',
          description: { text: teaser.slice(0, 256) },
          originalUrl: artUrl,
          title:       { text: article.title.slice(0, 400) },
        }],
      },
    },
    visibility: { 'com.linkedin.ugc.MemberNetworkVisibility': 'PUBLIC' },
  };

  try {
    const res  = await fetch('https://api.linkedin.com/v2/ugcPosts', {
      method:  'POST',
      headers: {
        Authorization:  `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-Restli-Protocol-Version': '2.0.0',
      },
      body: JSON.stringify(payload),
    });
    const text = await res.text();
    if (!res.ok) throw new Error(text);
    const json = JSON.parse(text);
    return { platform: 'linkedin', ok: true, id: json.id };
  } catch (err) {
    return { platform: 'linkedin', ok: false, error: err.message };
  }
}

// ─── Threads ──────────────────────────────────────────────────────────────────

async function postToThreads(article, teaser, artUrl) {
  const token = readFile(THREADS_TOKEN_FILE);
  if (!token) return { platform: 'threads', skipped: true, reason: 'missing threads-token file' };
  const userId = THREADS_USER_ID;

  const text   = buildPostText(article, teaser, artUrl, 500);
  const imgSrc = imageUrl(article);

  try {
    // Step 1 — create container
    const createParams = new URLSearchParams({
      media_type:   'IMAGE',
      image_url:    imgSrc,
      text,
      access_token: token,
    });
    const createRes  = await fetch(`https://graph.threads.net/v1.0/${userId}/threads`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    createParams,
    });
    const createJson = await createRes.json();
    if (!createRes.ok || createJson.error) throw new Error(`Container error: ${JSON.stringify(createJson.error ?? createJson)}`);

    const creationId = createJson.id;

    // Small wait — Threads recommends ~30s before publishing; use 5s in practice
    await new Promise(r => setTimeout(r, 5000));

    // Step 2 — publish
    const publishParams = new URLSearchParams({ creation_id: creationId, access_token: token });
    const pubRes  = await fetch(`https://graph.threads.net/v1.0/${userId}/threads_publish`, {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    publishParams,
    });
    const pubJson = await pubRes.json();
    if (!pubRes.ok || pubJson.error) throw new Error(`Publish error: ${JSON.stringify(pubJson.error ?? pubJson)}`);

    return { platform: 'threads', ok: true, id: pubJson.id };
  } catch (err) {
    return { platform: 'threads', ok: false, error: err.message };
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const articles = JSON.parse(readFileSync(ARTICLES_DB, 'utf8'));
  const posted   = loadPosted();

  let article;
  if (FORCE_SLUG) {
    article = articles.find(a => a.slug === FORCE_SLUG);
    if (!article) {
      console.error(`Slug not found: ${FORCE_SLUG}`);
      process.exit(1);
    }
  } else {
    // Newest unposted with a real teaser (skip boilerplate/junk articles)
    const candidates = [...articles]
      .sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt))
      .filter(a => !posted[a.slug]);

    for (const candidate of candidates) {
      const t = extractTeaser(candidate.slug);
      if (t.length > 30) { article = candidate; break; }
      console.log(`  skip (no real teaser): ${candidate.slug}`);
    }
  }

  if (!article) {
    console.log('No new articles with real content to post.');
    return;
  }

  const artUrl = `${SITE_BASE}/articles/${article.slug}`;
  const teaser = extractTeaser(article.slug);

  console.log(`\nPosting: ${article.title}`);
  console.log(`URL:     ${artUrl}`);
  console.log(`Image:   ${imageUrl(article)}`);
  console.log(`Teaser:  ${teaser.slice(0, 80)}…`);
  console.log(`Dry run: ${DRY_RUN}\n`);

  if (DRY_RUN) {
    const previewText = buildPostText(article, teaser, artUrl);
    console.log('─── Preview ───────────────────────────────────────');
    console.log(previewText);
    console.log('────────────────────────────────────────────────────');
    return;
  }

  // Post to all platforms in parallel (Threads last due to its wait)
  const [tw, fb, ig, li] = await Promise.all([
    postToTwitter(article, teaser, artUrl),
    postToFacebook(article, teaser, artUrl),
    postToInstagram(article, teaser, artUrl),
    postToLinkedIn(article, teaser, artUrl),
  ]);
  const th = await postToThreads(article, teaser, artUrl);

  const results = [tw, fb, ig, li, th];

  for (const r of results) {
    const icon = r.skipped ? '⏭' : r.ok ? '✓' : '✗';
    const detail = r.skipped ? r.reason : r.ok ? r.id : r.error;
    console.log(`  ${icon} ${r.platform.padEnd(10)} ${detail}`);
  }

  markPosted(article.slug, results);

  const failed = results.filter(r => !r.ok && !r.skipped);
  if (failed.length) {
    console.error(`\n${failed.length} platform(s) failed. Slug NOT fully marked posted.`);
    process.exitCode = 1;
  } else {
    console.log('\nDone.');
  }
}

main().catch(err => { console.error(err); process.exit(1); });
